package io.github.nickm980.smallville.memory;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

import io.github.nickm980.smallville.entities.SimulationTime;
import io.github.nickm980.smallville.math.SmallvilleMath;

/**
 * Observations are past events (including dialog / conversations) that the
 * agent is aware of. There is a decay which makes older memories easier to
 * forget
 */
public class Observation extends Memory implements TemporalMemory {

    private final LocalDateTime time;
    /**
     * If the observation wasn't generated by the server then it should be a
     * reactable observation
     */
    private boolean isGenerated;
    /**
     * True when this observation is a line of dialog copied into a
     * participant's memory stream from a conversation, rather than an
     * observation of an activity/event.
     */
    private boolean isDialog;

    public Observation(String description) {
	super(description);
	time = SimulationTime.now();
	this.isGenerated = false;
    }

    public Observation(String description, LocalDateTime time, int importance) {
	super(description);
	super.setImportance(importance);
	this.time = time;
    }

    public boolean isReactable() {
	return isGenerated;
    }

    public void setReactable(boolean isGenerated) {
	this.isGenerated = isGenerated;
    }

    public boolean isDialog() {
	return isDialog;
    }

    public void setDialog(boolean isDialog) {
	this.isDialog = isDialog;
    }

    @Override
    public LocalDateTime getTime() {
	return time;
    }

    @Override
    double getRecency() {
	return recencyOf(time);
    }
}